### ISSUE TITLE
perl-base copyright is missing

### ISSUE THREAD

**Issue by eigood** [debuerreotype/docker-debian-artifacts#10]
perl-base.deb has a symlink at /usr/share/doc/perl-base -> perl.  This is allowed by policy.  But the dpkg.cfg.d/docker excludes all /usr/share/doc/*, but then includes copyright files.  This has the side-effect of not extracting symlinks.

Policy allows for PkgA to symlink PkgB, *if* they are from the same source.  So now the copyright file is not available at /usr/share/doc/perl-base/copyright, because the symlink wasn't created.

This also at least applies to libstdc++6, libgcc1, and libcursesw5.

**Comment by tianon** [comment]
Oh, very interesting edge case!

Just for reference, here's the relevant section of policy: (https://www.debian.org/doc/debian-policy/ch-docs.html#s-copyrightfile)

> `/usr/share/doc/package` may be a symbolic link to another directory in `/usr/share/doc` only if the two packages both come from the same source and the first package Depends on the second. These rules are important because `copyright` files must be extractable by mechanical means.

The bulk of our excludes/includes (which come canonically from https://github.com/debuerreotype/debuerreotype/blob/ce5cb9f5a0eb2aa171587339d50126139750a6d8/scripts/debuerreotype-slimify / https://github.com/debuerreotype/debuerreotype/blob/ce5cb9f5a0eb2aa171587339d50126139750a6d8/scripts/.slimify-excludes) were inspired by https://wiki.ubuntu.com/ReducingDiskFootprint#Documentation.

I could've sworn there was a similar example in the Debian wiki somewhere (or a section in policy legitimizing exclusion of all docs except `copyright` files), but couldn't find it in my preliminary searching.

For further reference, https://github.com/tianon/docker-brew-debian/issues/48 is where this idea was originally discussed, and to be clear, this only affects the `slim` variants of our Debian images.

In order to determine whether our deletion code (https://github.com/debuerreotype/debuerreotype/blob/ce5cb9f5a0eb2aa171587339d50126139750a6d8/scripts/debuerreotype-slimify#L37-L52) matches `dpkg`'s behavior, I did `apt-get install --reinstall perl-base` in `debian:stretch-slim`, and it did re-create the `/usr/share/doc/perl-base -> perl` symlink, so we definitely need to adjust `debuerreotype`'s behavior to match.  I wonder how difficult it would be to find the exact code path within `dpkg` which handles `path-exclude`/`path-include` so we can try to mimic it better there (or at least figure out whether it has specific special casing for symlinks, etc -- ie, why it keeps this symlink when a strict interpretation of the `path-exclude`/`path-include` behavior shouldn't).

**Comment by tianon** [comment]
In https://manpages.debian.org/stretch/dpkg/dpkg.1.en.html, we find the following note:

> Note: the current implementation might re-include more directories and symlinks than needed, to be on the safe side and avoid possible unpack failures; future work might fix this.

... which is then followed by an example of:

> `--path-exclude=/usr/share/doc/*`
> `--path-include=/usr/share/doc/*/copyright`

:smile:

**Comment by tianon** [comment]
I think https://sources.debian.net/src/dpkg/1.18.24/src/filters.c/#L96-L97 is the relevant bit of code:
```c
	/* We need to keep directories (or symlinks to directories) if a
	 * glob excludes them, but a more specific include glob brings back
	 * files; XXX the current implementation will probably include more
	 * directories than necessary, but better err on the side of caution
	 * than failing with “no such file or directory” (which would leave
	 * the package in a very bad state). */
	if (skip && (ti->type == TAR_FILETYPE_DIR ||
	             ti->type == TAR_FILETYPE_SYMLINK)) {
```
(so it would seem that our "delete all the things" code needs to be more forgiving of symlinks initially, and then our second-pass which currently deletes empty directories we also need to delete dangling symlinks)

**Comment by eigood** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871420

I filed an issue against dpkg as well, for having poor docs.

**Comment by eigood** [comment]
Fyi, I'm also doogie@debian.org, and have done previous work in dpkg and debbugs code bases.

**Comment by tianon** [comment]
https://github.com/debuerreotype/debuerreotype/pull/15 is my first pass at fixing this -- it appears to generate the correct result (`output/20170807/amd64/stretch/slim/rootfs.tar.xz` included `usr/share/doc/perl-base` properly), so I think I've got it right. :+1:

**Comment by eigood** [comment]
This will take me a bit to verify; I actually discovered it while attempting to extract license data from library/nginx, which is based on stretch-slim, so I've got to rebuild several layers of images.

**Comment by tianon** [comment]
This should've been in the last update to the image. :+1:
