### ISSUE TITLE
debian:buster-slim with security vulnerability CVE-2020-10878

### ISSUE THREAD

**Issue by achoi288** [debuerreotype/docker-debian-artifacts#100]
Are there plans to fix this? If so, any estimated timeline?

**Comment by tianon** [comment]
Looking at https://security-tracker.debian.org/tracker/CVE-2020-10878, this is not fixed in Buster, and looking at the following note from that page, the Debian Security team considers it a minor issue, so the likelihood of it being fixed in Debian Buster in the future is very low:

```
[buster] - perl <no-dsa> (Minor issue)
```

**Comment by gholt** [comment]
Hi, I'm curious about this, perhaps it was fixed right after your comment? It appears fixed now and the severity is even considered "high".

**Comment by tianon** [comment]
Interesting -- my guess is that it's related to the 10.5 release over the weekend.  The Security Team's notes appear at the bottom of the page there, so their `<no-dsa>` note is simply removed, so it was likely fixed via a normal stable update (instead of as a security update).

Regardless, there are new builds in-progress for 10.5 which should include this fix. :+1:
