### ISSUE TITLE
CVE-2020-14356 in buster-slim

### ISSUE THREAD

**Issue by mankee10200** [debuerreotype/docker-debian-artifacts#103]
We are trying to build an image using `debian:buster-slim` and we are seeing this critical vulnerability - it has been fixed in buster https://security-tracker.debian.org/tracker/CVE-2020-14356

**Comment by JoelLinn** [comment]
Where exactly do you see that vulnerability?
To my understanding it is a pure kernel bug. As docker containers use the host's kernel they do not include any kernels and this bug is irrelevant.

**Comment by mankee10200** [comment]
We have a Clair scanner that picks it up whilst building `varnish:6.5.1` (https://hub.docker.com/layers/varnish/library/varnish/6.5.1/images/sha256-3ae450886dc562faf9e510979f26ee7ec10d72c120cad4b48459aaadebbd7d6d?context=explore) which itself uses `debian:buster-slim`

**Comment by yosifkit** [comment]
1. it is not an issue in the `debian:buster-slim` image (no packages from on the [`linux` source package](https://packages.debian.org/source/buster/linux) are installed)
	```console
	$ docker pull debian:buster-slim
	10:29:16 ... $ docker pull debian:buster-slim
	buster-slim: Pulling from library/debian
	Digest: sha256:b527bec3708ee1fe2ffb4625d742a60bb45b06064e7c64a81b16550fe42710f5
	Status: Image is up to date for debian:buster-slim
	docker.io/library/debian:buster-slim
	$ docker run -it --rm debian:buster-slim
	root@dbe9e4d84383:/# dpkg -l | grep linux
	ii  libselinux1:amd64       2.8-1+b1               amd64        SELinux runtime shared libraries
	ii  util-linux              2.33.1-0.1             amd64        miscellaneous system utilities
	```
2. This vulnerability in the *kernel* does not affect the headers files (there is no kernel installed in the image)
	```console
	 $ docker run -it --rm varnish:6.5.1 bash
	Unable to find image 'varnish:6.5.1' locally
	6.5.1: Pulling from library/varnish
	d121f8d1c412: Already exists 
	1094de8696c7: Pull complete 
	016497474304: Pull complete 
	Digest: sha256:f0cdc07eb324dc606f0f4ddac694175c46bf2b9a89270f1a66eb5c8dc3feff36
	Status: Downloaded newer image for varnish:6.5.1
	root@c72f0570914b:/etc/varnish# dpkg -l | grep linux
	ii  binutils-x86-64-linux-gnu 2.31.1-16              amd64        GNU binary utilities, for x86-64-linux-gnu target
	ii  libselinux1:amd64         2.8-1+b1               amd64        SELinux runtime shared libraries
	ii  linux-libc-dev:amd64      4.19.146-1             amd64        Linux support headers for userspace development
	ii  util-linux                2.33.1-0.1             amd64        miscellaneous system utilities
	root@c72f0570914b:/etc/varnish# 
	```
3. Even if there was a known exploit, this could not be done from a container since they are not normally given `CAP_SYS_BOOT` ([Capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html)) and [Docker's default seccomp](https://github.com/moby/moby/blob/ffd0861b8b5181c90dad4a2b13ad042d26d8996a/profiles/seccomp/default.json#L663-L676) only allows reboot when the container has `CAP_SYS_BOOT`.

	> A flaw null pointer dereference in the Linux kernel cgroupv2 subsystem in versions before 5.7.10 was found in the way when reboot the system.
	>
	> \- https://security-tracker.debian.org/tracker/CVE-2020-14356

A CVE doesn't imply having an actual vulnerability, and often is even a false positive (given how most distributions handle versioning/security updates in stable releases). If there are actionable items we can resolve, we're happy to do so (and do so actively). We update all Debian based images to include any updates in apt packages at least monthly (we regenerate the base images and then rebuild all dependent images).

See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
And https://github.com/docker-library/postgres/issues/286#issuecomment-302512767 docker-library/openjdk#161, docker-library/openjdk#112, docker-library/postgres#286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, docker-library/openjdk#185.
