### ISSUE TITLE
Vulnerabilities present in debian:latest image, CVE-2019-19814

### ISSUE THREAD

**Issue by gauravdutt13** [debuerreotype/docker-debian-artifacts#114]
Hi ,

While scanning images in AWS ECR , I found that images have some vulnerabilities. Critical one is below
```
In the Linux kernel 5.0.21, mounting a crafted f2fs filesystem image can cause __remove_dirty_segment slab-out-of-bounds write access because an array is bounded by the number of dirty types (8) but the array index can exceed this.
```

FROM debian:latest

```
 uname -r
4.14.209-160.335.amzn2.x86_64
```

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Any help will be appreciated to resolve this vulnerability .
<img width="1427" alt="Screenshot 2021-02-03 at 8 48 20 PM" src="https://user-images.githubusercontent.com/72395689/106767759-37440e80-6661-11eb-8656-47245ce76d64.png">

**Comment by JoelLinn** [comment]
**This issue is invalid** as there is no kernel inside the docker image. The kernel the container uses and "sees" is the one from the host machine (That is what makes containers and VMs different), for example for me it is:

```
$ sudo docker run --rm debian:latest uname -r 
5.8.0-41-generic
```

If your host machines OS is still under support and kept up to date, the bug has very likely been fixed upstream.

Also, it is _usually_ not possible to call [mount()](http://manpages.ubuntu.com/manpages/hirsute/man2/mount.2.html) from inside a container (Except CAP_SYS_ADMIN was granted to the container), so even if a kernel is vulnerable to this CVE an attacker would need another vulnerability or side channel to exploit it.

**Comment by tianon** [comment]
Indeed -- I'd suggest reporting this to ECR as a false positive.  There is no Linux kernel in any of the images we publish.

**Comment by stappersg** [comment]
> **This issue is invalid** as there is no kernel inside the docker
> image. The kernel the container uses and "sees" is the one from the
> host machine.

+1


Request to issue reporter:  Please close this issue.
