### ISSUE TITLE
debian:bullseye (11) doesn't have iproute2 installed (providing the ip command)

### ISSUE THREAD

**Issue by tuxayo** [debuerreotype/docker-debian-artifacts#117]
Debian 10 for example has it. Is iproute2 deprecated and replaced?

**Comment by tianon** [comment]
This was intentional -- see https://github.com/debuerreotype/debuerreotype/pull/101.

(The short answer being that `ip` and `ping` are *not* installed in a stock `debootstrap --variant=minbase`, so it has always been a source of tension with other Debian Developers and user expectations that we included them explicitly -- `iproute2` is not deprecated.)

If the `ip` command is something that's necessary for your use case, I would suggest adding something like the following to your own `Dockerfile`s to compensate:

```dockerfile
FROM debian:bullseye
RUN apt-get update && apt-get install -y iproute2
```

**Comment by tuxayo** [comment]
Thanks for the explanation and thanks for your work. Have a nice day :)
