### ISSUE TITLE
The slim image is fat

### ISSUE THREAD

**Issue by hginzel** [debuerreotype/docker-debian-artifacts#119]
There are fdisk, e2fsprogs, ncurses and man pages in the **slim** image. Who needs it in _docker_ image? The standard dependencies are for classical system, not for `chroot` environment or `docker` image.

See
* https://github.com/docker-library/python/issues/587
* https://www.dajobe.org/blog/2015/04/18/making-debian-docker-images-smaller/
* https://unix.stackexchange.com/questions/232800/debian-unnecessary-essential-packages-in-a-chroot-environment

**Comment by mt-clearhaus** [comment]
Regarding `util-linux` and `fdisk`, @yosifkit has provided insightful answers in https://github.com/docker-library/python/issues/587, e.g. https://github.com/docker-library/python/issues/587#issuecomment-791718903. It seems things will be improved in Bullseye.

**Comment by tianon** [comment]
Indeed, as noted in that other thread, the way things here will get better is by shrinking the set/size of "essential" packages in Debian itself.

If we were to go against the wishes/configurations of the larger project and remove these packages from our images, we'd be subjecting our users to unique bugs in any packages that are depending on these "essential" packages (because explicitly specifying essential packages in `Depends:` is not required).
