### ISSUE TITLE
Outstanding CVEs in buster and buster slim images

### ISSUE THREAD

**Issue by vivekjilla** [debuerreotype/docker-debian-artifacts#120]
Debian released a openssl security update patching some of the issues, as per https://lists.debian.org/debian-security-announce/2021/msg00035.html

Can we get those updates in for the docker images as well? https://hub.docker.com/_/debian/?tab=tags&page=1&ordering=last_updated&name=buster

Thanks!

**Comment by tianon** [comment]
We are roughly due for an update, so that will likely happen sometime this week, but I'd like to highlight the following bits from the upstream advisories in the meantime (which from my understanding, make these both somewhat less than critical severity):

https://www.openssl.org/news/secadv/20191206.txt

> However, for an attack the target would have to re-use the DH512 private key, which is not recommended anyway. Also applications directly using the low level API BN_mod_exp may be affected if they use BN_FLG_CONSTTIME.

https://www.openssl.org/news/secadv/20210216.txt

> The function X509_issuer_and_serial_hash() is never directly called by OpenSSL itself so applications are only vulnerable if they use this function directly and they use it on certificates that may have been obtained from untrusted sources.

**Comment by csMACnz** [comment]
I am also seeing https://nvd.nist.gov/vuln/detail/CVE-2021-24031 and https://nvd.nist.gov/vuln/detail/CVE-2021-24032 alerted on in some upstream images that depend on the base image `amd64/debian:buster-slim` around zstd.

It would be great to see another release to address these.

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/9778 :+1:
