### ISSUE TITLE
An /etc/hosts file is not included, causing localhost resolution to fail on some platforms

### ISSUE THREAD

**Issue by anoadragon453** [debuerreotype/docker-debian-artifacts#127]
An `/etc/hosts` file is not included in the resulting image, which [we found](https://github.com/matrix-org/synapse/issues/9764) can cause problems on container systems that don't populate `/etc/hosts` automatically - namely Docker on Windows.

The same user in the linked issue did not have any problems with images based on alpine, which do include an `/etc/hosts` file with the following contents in their [distribution image](https://github.com/alpinelinux/docker-alpine/blob/v3.13/x86_64/Dockerfile):

```
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain
```

Adding this file would allow resolution of `localhost` on these systems to work, however I do not know whether not including the file was a conscious decision or not.

**Comment by tianon** [comment]
It was definitely a conscious decision because Docker itself always mounts over the top of `/etc/hosts`, and there have been issues previously with images providing some of the files that Docker then overlays. :confused:

I see in https://github.com/matrix-org/synapse/issues/9764 that this is only when using LCOW, which is explicitly experimental -- see also https://github.com/docker/for-win/issues/6470#issuecomment-620466429 for a more "official" response around this. :grimacing:

I'd say this is firmly a bug in the LCOW implementation, since even lower-level container runtimes like `containerd`'s CRI will add `/etc/hosts`, but I'm unfortunately not sure whether there will be any appetite from either the Docker or Microsoft ends of this to fix it. :disappointed:

**Comment by anoadragon453** [comment]
Thank you for the detailed response and the context!

Given the response from upstream, it sounds like there's not much we can do here. We'll acknowledge it in documentation and point towards alternatives. Thanks again!
