### ISSUE TITLE
Vulnerability fix for perl in jessie

### ISSUE THREAD

**Issue by mt-clearhaus** [debuerreotype/docker-debian-artifacts#13]
See https://www.debian.org/security/2017/dsa-3982

> For the oldstable distribution (jessie), these problems have been fixed in version 5.20.2-3+deb8u9.

The debian:jessie image should be rebuilt into Docker hub to make sure it uses perl-base 5.20.2-3+deb8u9.

```
$ docker pull debian:jessie
jessie: Pulling from library/debian
Digest: sha256:90f44b88dd8d80bd0fca08c728591fbc43fe36feed3d38428ae1d6d375d96689
Status: Image is up to date for debian:jessie

$ docker run --rm -it debian:jessie bash -c 'dpkg -l | grep perl-base'
ii  perl-base   5.20.2-3+deb8u8   amd64   minimal Perl system
```

Thanks.

**Comment by yosifkit** [comment]
Considering that we rebuild all the Debian distros at the same time and that Stretch will need this as well, I'd like to hold this off until after 7th October 2017.  We try to rebuild the images at least every month (or for major vulnerabilities and releases) and that is the date planned for a new Stretch [release](https://release.debian.org/) (9.2).  I'm not sure that this DSA warrants a build now and on Monday, since using a literal user-supplied regex in perl from some remote facing application is a much less often occurrence than something like openssl.

**Comment by mt-clearhaus** [comment]
That sounds very reasonable :slightly_smiling_face: Thank you very much!

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3558 :+1:
