### ISSUE TITLE
Please usrmerge Bullseye and above

### ISSUE THREAD

**Issue by geofft** [debuerreotype/docker-debian-artifacts#131]
For consistency, it seems like it would be a good idea to make it so that debian:testing (and soon debian:11) is usrmerge'd - debian-installer defaults to usrmerge and doesn't give you an option for an unmerged usr. Right now it looks like debian:testing is unmerged.

**Comment by geofft** [comment]
Linking to #60 - I think it makes sense that it was disabled for Buster (and should remain disabled), but I think it should be enabled for Bullseye if I understand the situation right.

**Comment by tianon** [comment]
For installed systems, I totally agree -- however, the place this gets complicated for the Docker images is that they're very, very often used as both "installed system" and "buildd", and I do not believe it's safe in Bullseye to build packages for general consumption on a usrmerge'd chroot, right?
(https://lists.debian.org/debian-devel-announce/2019/03/msg00001.html - ``Issues from "merged `/usr`"`` heading)

That being said, I think the conclusion in https://bugs.debian.org/978636#178 is that bookworm+ is totally safe to go full-usrmerge? :pray: :sweat_smile:

**Comment by geofft** [comment]
Hmm, that's a reasonably compelling argument, for bullseye at least (and I agree that on bookworm, if merged usr is mandatory, then these problems don't arise).

My motivation is that that the interactive Docker image doesn't act like an interactive installed system, but I admit that's less compelling of an argument. Thanks for thinking about it though!

**Comment by geofft** [comment]
I'm not sure why I didn't think of this earlier, but `apt update; apt install usrmerge` works. So that's another argument in favor of keeping the image unmerged; it's easy to run that if you want to see what the merged layout looks like, but there's no conversion in the other direction (unless you count `dpkg-fsys-usrunmess`, I guess).

I think a working Dockerfile to poke at a usrmerged system is
```
FROM debian:testing # or 11, or unstable, or whatever
RUN echo debconf usrmerge/autoconvert select true | debconf-set-selections && apt-get update && apt-get -y install usrmerge
```

**Comment by zeha** [comment]
From my experience it's easy enough to build packages on a non-usr-merged system and still produce packages that will not work on them. Its certainly easier (and required by some tools) to build on non-usr-merged to support non-usr-merged, but its not a definite solution. If Docker images are supposed to be usable as build platforms ("buildd"), then they have to stay non-merged for now, even though this will have problems for non-build usages.

**Comment by smcv** [comment]
As a first go at this, I think wait until we have a better picture of how many packages are still misbuilt with merged-/usr, and err on the side of unmerged because `apt install usrmerge` is easy to do.

**Comment by tianon** [comment]
Makes sense; your input (both here and the larger project) is very much appreciated! ❤️

**Comment by bobrik** [comment]
Doesn't look like usrmerge works on overlayfs:

* https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1848199.html

**Comment by tianon** [comment]
More "canonical" link for the above discussion: https://bugs.debian.org/1008202#10

The discussion there is that the usrmerge _conversion_ doesn't work on overlayfs (but a pre-usrmerged-image itself does work just fine -- they're just totally normal vanilla symlinks after all).

**Comment by smcv** [comment]
We talked about this more recently and my suggestion is now this: https://lists.debian.org/debian-ctte/2022/07/msg00034.html

**Comment by tianon** [comment]
As always, really appreciate you sharing your thoughts and perspective! :bow:

I'll reply here since it doesn't seem like anyone in the CTTE objects or has input on your proposed plan so this feels like a more appropriate place to continue that discussion. :+1:

I think your plan sounds great -- the only place I'm going to have a minor deviation (that shouldn't affect the end result) is that I plan to duplicate the logic for when/where to apply `--merged-usr` to avoid a versioned dependency on `debootstrap` (and so we can more easily apply a bit more nuance such as leaving `bookworm` unmerged for now).  I plan to have a PR up ASAP so this can get into the rebuild I'll likely do next week. :eyes:

**Comment by tianon** [comment]
The (hopefully-final) PR on this subject is up at https://github.com/debuerreotype/debuerreotype/pull/143 now :eyes:

(I also included some extra context over there about why I think our next round of image builds is the time to finally apply this to `bookworm` :+1:)

**Comment by MichaIng** [comment]
Is there a workaround for applying `usrmerge` on a Debian Bullseye Docker container? We just face the issue on MariaDB Salsa CI pipelines that testing distro upgrades Bullseye => Bookworm does not work. This is since `usrmerge` is pulled as dependency on Bookworm (`usr-is-merged` cannot be installed as long as the system is not actually usr-merged), but fails/denies to apply/install so that the whole distro-upgrade fails.

The ability for Debian package maintainers to test the upcoming distro upgrade would be quite helpful, and the official Debian Docker containers are a popular platform for CI/CD pipelines. Probably a set of dedicated usr-merged Bullseye containers could be released?
