### ISSUE TITLE
Debian 8?

### ISSUE THREAD

**Issue by jas4711** [debuerreotype/docker-debian-artifacts#132]
Hi.  I'm using the "oldoldstable" image and it is quite useful to test building of software on "older" Debians for GNU InetUtils (and several other packages) -- see https://gitlab.com/jas/inetutils/-/pipelines --but I have noticed that these are no longer mentioned on https://hub.docker.com/_/debian/ -- is there a reason for this?  I know the release is probably not supported upstream anymore (I guess?), but it still serves a good purpose to test building.  It works great for me, and has done so for a long time.  Would you consider supporting it officially again?

**Comment by yosifkit** [comment]
No, there is no support from upstream for continuing it. Debian 8 (Jessie) reached end of life on 2018-06-17 and end of LTS on 2020-06-30 (https://wiki.debian.org/DebianReleases). The Jessie images will likely only work until the apt repos are removed from `deb.debian.org` and they definitely don't get any updates, security or otherwise. For example, the `debian:wheezy` image fails to `apt-get update` since the apt repos are unavailable.

**Comment by tianon** [comment]
You might find https://hub.docker.com/r/debian/eol interesting/useful if you need to continue using EOL releases.

**Comment by jas4711** [comment]
> You might find https://hub.docker.com/r/debian/eol interesting/useful if you need to continue using EOL releases.

Ah wonderful, thank you!
