### ISSUE TITLE
debian:stable-slim uses unavailable apt security repository

### ISSUE THREAD

**Issue by bantu** [debuerreotype/docker-debian-artifacts#134]
Running `apt-get update -qq` I am seeing
```
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
```

This seems to be due to the fact that the location of the security repository has changed. See https://wiki.debian.org/NewInBullseye

**Comment by joachim-isaksson** [comment]
The problem seems to be related to that the tags stable/stable-slim are still Buster (Debian 10) versions, a rebuild of the image with the current stable Bullseye should fix the problem. 

The security repo has been updated with the new stable structure, but the images are a bit outdated and refer to the old directory structure.

**Comment by tianon** [comment]
I'll be working on an updated build first thing tomorrow morning.

(What I would suggest in the meantime and even generally is using either
"buster" or "bullseye" explicitly instead of the "stable" square wheel, as
both tags should still be functioning properly.)

**Comment by boindil** [comment]
Seems to have been renamed to 

https://security.debian.org/debian-security/dists/stable-security/updates/InRelease

**Comment by tianon** [comment]
Rebuilds are in progress.

For what it's worth, this was fixed in our tooling back in https://github.com/debuerreotype/debuerreotype/pull/65 -- the nature of the `stable` tag however is that `sources.list` points to the `stable` alias, so there's this short period between the release on Saturday and the rebuilds the following Monday where this rename breaks that one tag (and this is why no other tag is affected).

This is honestly probably a harbinger of things to come for anyone who's been broken by it since it's definitely not the only change in the distribution from Buster to Bullseye; hence why I call this a "square wheel" -- it's _technically_ a rolling release tag, but when it rolls, it rolls like a square wheel and clunks down with a huge set of changes all at once.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/10730 :+1:
