### ISSUE TITLE
Please add procps by default

### ISSUE THREAD

**Issue by nanonyme** [debuerreotype/docker-debian-artifacts#146]
Podman top expects ps to be in the image. Since Debian ships podman but not Docker, it seems reasonable to me to tweak image to work better with Debian tooling.

**Comment by tianon** [comment]
See https://github.com/tianon/docker-brew-debian/issues/13, https://github.com/tianon/docker-brew-debian/issues/14, #5, #20, #80, and even https://github.com/debuerreotype/debuerreotype/pull/101.

Not including `procps` is definitely very intentional, as it's not part of the "essential" set (and thus is not installed with a standard `debootstrap --variant=minbase`).

As to the (fairly unrelated) claim that Debian ships with podman but not Docker, where are you getting that from?  https://packages.debian.org/search?keywords=docker.io

**Comment by nanonyme** [comment]
I see, thanks for the pointer for the justification, that is quite clear. Latter is on me, good to know both are included.
