### ISSUE TITLE
Getting vulnerabilities while installing packages in debian image

### ISSUE THREAD

**Issue by bhavuk7** [debuerreotype/docker-debian-artifacts#160]
while creating docker image using debian as base image, trying to install packages but updated versions are not getting installed with it and getting vulnerabilities while docker scan.
debian image which is used in Dockerfile- debian:buster-slim
Below are the packages i'm installing in docker image-
```dockerfile
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    ca-certificates \
    cmake \
    make \
    tar \
    cron \
    libssl-dev \
    libsasl2-dev \
    pkg-config \
    libsystemd-dev \
    zlib1g-dev \
    libpq-dev \
    postgresql-server-dev-all \
    flex \
    bison \
    && curl -L -o "/tmp/fluent-bit.tar.gz" ${FLB_SOURCE} \
    && cd tmp/ && mkdir fluent-bit \
    && tar zxfv fluent-bit.tar.gz -C ./fluent-bit --strip-components=1 \
    && cd fluent-bit/build/ \
    && rm -rf /tmp/fluent-bit/build/*
```

**Comment by yosifkit** [comment]
Are you certain that the packages have fixes available?  Since Debian is a volunteer driven distribution, the Debian Security team have to maximize their impact when addressing security fixes. Because of Debian policies regarding package bumps in stable releases, they often have to backport any upstream-provided patches so as to not cause a possibly incompatible version bump. So for security fixes that they deem minor (regardless of the CVSS score), they often mark them as `<no-dsa> (Minor issue)` (e.x. https://security-tracker.debian.org/tracker/CVE-2022-27405).

**Comment by kgreunke** [comment]
There is a high/critical CVE regarding libssl that has an updated package currently not in the bullseye-slim image and probably others.  Debian bugtracker here https://security-tracker.debian.org/tracker/CVE-2022-1292

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/12531 :+1:
