### ISSUE TITLE
Debian OS  security Vulnerabilities

### ISSUE THREAD

**Issue by anandarca** [debuerreotype/docker-debian-artifacts#163]
Hi,

security vulnerabilities.

The below 2 Debian OS docker images are used & below vulnerabilities are reported by Microsoft Defender in ACR. The severity level is High. Please let me know if the below issues are fixed & available in tags.

debian:buster-slim
debian:bullseye-slim

The below CVE for both buster-slim & bullseye-slim : 
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2068  ( high)
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15778  ( medium)

the below CVE for debian:buster-slim :

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14145 ( medium)

We have an high priority incident to fix them on high priority from security compliance so please advise.

Regards,
Ananda

**Comment by yosifkit** [comment]
If there is a fix available in the respective releases (see the Debian security tracker links below), then they will be part of all official images once https://github.com/docker-library/official-images/pull/12776 is merged and all the rebuilds are complete.

- https://security-tracker.debian.org/tracker/CVE-2022-2068
- https://security-tracker.debian.org/tracker/CVE-2020-15778 (should likely report to your security scanner that this is a false positive since the CVE is disputed)
- https://security-tracker.debian.org/tracker/CVE-2020-14145
