### ISSUE TITLE
openssl 1.1.1 going to end of life

### ISSUE THREAD

**Issue by gopa810** [debuerreotype/docker-debian-artifacts#192]
With OpenSSL 1.1.1 going to End of Life, are you considering to use OpenSSL 3.0 in Debian images?
https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/#:~:text=OpenSSL%201.1.1%20was%20released,security%20fixes%20after%20that%20date.

**Comment by JoelLinn** [comment]
No because this is not the place to discuss the contents of the debian package repository. You need to raise this with the debian (openssl) maintainers. They will not switch major package version for a distribution release though. They will however do their best to backport newer security fixes to their older (EOL) packages for as long as the distribution is supported. If you want the newest major versions, you need to switch to a newer debian release (once its available).
