### ISSUE TITLE
Unable to download bookworm artifacts 

### ISSUE THREAD

**Issue by hjimenez-godaddy** [debuerreotype/docker-debian-artifacts#233]
Hello Guys, I hope you're doing great. 

I was using this script for a few local builds of multiple Debian images, but today I'm getting the following errors : 

`artifacts/bookworm/slim/rootfs.tar.xz: FAILED open or read`

It looks like the script fails to download the debain12 version is this currently deprecated ?

Regards, 
H

**Comment by tianon** [comment]
See https://github.com/debuerreotype/docker-debian-artifacts/pull/186 (and frankly the dist branches which contain the pre downloaded artifacts)

That being said, I'd suggest using something like [`crane export`](https://github.com/google/go-containerregistry/blob/v0.20.2/cmd/crane/doc/crane_export.md) instead if what you need is just a rootfs tarball.  To put that another way, you're not actually gaining anything by "building" via the scripts here, because they just download the tarballs from somewhere else, without any verification or guarantees.
