### ISSUE TITLE
Please switch to HTTPS in sources.list

### ISSUE THREAD

**Issue by stapelberg** [debuerreotype/docker-debian-artifacts#28]
E.g. https://github.com/debuerreotype/docker-debian-artifacts/blob/dist-amd64/sid/rootfs.sources-list currently contains a http:// URL.

As per https://blog.packagecloud.io/eng/2018/02/21/attacks-against-secure-apt-repositories/, it is generally advisable to use https://.

Could we ship the images with https:// URLs by default please?

**Comment by tianon** [comment]
Default installs of Debian still use http, don't they?  Is that a planned
change for the installer?

**Comment by stapelberg** [comment]
Not sure. Must the docker image always trail the installer? It seems like we could make this change independently.

**Comment by alehaa** [comment]
@stapelberg Do you know if this conflicts with local APT-Caches using the DNS SRV records? I think this would force local caches to enable TLS, right?  In addition this would bypass simple HTTP caches. For environments using lots of packages (like CI) this could slow down the builds etc.

So I think the packages should be identical to the regular Debian installations, so the users don't get something they don't expect. However, there could be something like a separate, "hardened" image?

**Comment by stapelberg** [comment]
Can you explain in more detail what sort of cache you have in mind?

The caches I’m aware of (apt-cacher-ng) require you to change the URL in your sources.list, so my suggestion doesn’t change anything in that regard.

**Comment by alehaa** [comment]
Recent versions of apt check the SRV records of the repositories to be used. This way, [deb.debian.org](http://deb.debian.org) tells apt to use the CDN servers. You can simply override this record with your cache server set (see the docs at deb.debian.org). I'm not sure if these would need a TLS certificate for their hostname or the name used in `sources.list`. For the later I can't get a TLS cert for an official Debian repository hostname.

Another way is to route apt's traffic with a transparent HTTP proxy to the cache server. This can't be used with HTTPS.

**Comment by stapelberg** [comment]
Thanks for elaborating. I don’t gather from the docs at deb.debian.org that it is recommended to rewrite the SRV record. Rather, the docs are saying that you can use either of the two hostnames in your sources.list directly.

In general, man-in-the-middle will not work with using TLS (neither on the HTTP nor on the DNS level). That’s the whole point, so I don’t think it should discourage us from pursuing the change I suggest.

**Comment by hmh** [comment]
**The whole security of apt is designed around the notion that the transports and remote data at rest (i.e. the mirror itself) can be insecure.**  As such, almost all the time any possible security gains one thinks she would get from **enabling https for apt** (not https in the general case) are merely illusory.

Enabling a https transport **for apt** gets you the following downsides, that are very unfortunately not widely understood by the userbase:

1. Much larger remote attack surface, due to the TLS, X.509 and ASN.1 layers required to speak https.  Every component on this layer had remotely-exploitable security issues in the past AFAIK.  It is almost certain that there will be zero-day security issues still waiting to be fixed on the TLS stacks;
1. Much more resource-intensive on the server side;
1. Unless specifically configured for the set of servers that are going to be used (certificate stapling, etc), it will depend entirely on the CA ecosystem to avoid MITM.  Maybe DANE+DNSSEC can be used by apt already, but that also counts as specifically configured at this time since neither DNSSEC or DANE are generally available in the Debian mirror network;
1. Installing https support enables "connection upgrades" attacks against the http transport, unless you configure apt to refuse to use https.  This allows an attacker to "upgrade" from http to https, in order to attack the TLS stack.  So, it exposes everyone to higher risk just by being present in the image (unless we configure apt to disable https, but then why would we include the https transport in the first place?);
1. It gets in the way of proxy-based caching, unless you configure the proxy for https-over-http;
1. It gets in the way of transparent caching.

Note that this also applies to the **tor** transport, but that one at least does provide strong privacy protection, unlike https (Debian package updates are practically the "walk in the park" case for network-flow-metadata-based traffic analysis. And https does not provide any protection against network flow tracking protection, **tor** does provide some).

Usually, we consider "privacy against unskilled attackers" and "getting around halfhearted corporate web filtering" the only possible valid use cases for **https in apt** (not https in general), neither of which appear to me to be relevant for the Debian docker images.  Everything else is, as far as I know, covered by the apt security model.

Due to the above, **IMHO,** the https transport should not be enabled by default in the docker images.

**Comment by stapelberg** [comment]
How specifically are the freeze attacks outlined by the article addressed by apt’s security model when not using https?

I understand your arguments, but would argue that these days, pretty much every single docker container is going to run some application software which involves https, so we already have a high interest in keeping TLS secure.

I’m not sure how common it is to actually have a caching proxy between Debian docker containers and a Debian mirror, as opposed to just having a local mirror, for example.

Also note that TLS is pretty cheap CPU-wise, these days: https://www.imperialviolet.org/2010/06/25/overclocking-ssl.html (from 8 years ago!), and I’m fairly confident that the CDNs behind deb.d.o are equipped to handle TLS. Other Debian mirrors are out of scope, as users would need to manually configure them anyway (and can then decide for themselves whether they want https or not).

**Comment by tianon** [comment]
On the subject of caching, one cannot easily use a local mirror with Docker images (especially not those intended to share, since nobody but you will have your local mirror, and nobody else's images will use your local mirror), so I think anyone doing any kind of local caching or mirror intended for use with Docker as well _has_ to be doing transparent caching.

In the official images, we use a transparent cache on every build server to dramatically increase build speed in many cases (especially for building very similar things like different versions of the same tool/language/etc), but we couldn't ask every image maintainer to use our cache explicitly in their `Dockerfile`s, and doing so would hamper the usefulness of our images to our users.

**Comment by stapelberg** [comment]
Okay, it seems like the transparent caching will prevent us from switching to https anytime soon. Closing.

**Comment by hmh** [comment]
@stapelberg: AFAIK, the APT security model shortens the available window for **silent** freeze attacks by refusing to operate on "outdated" metadata.  Of course, this requires that you don't disable this check (which deburreotype does, but AFAIK only while it is generating the image. apt-get update will have that still enabled), and that you're paying attention (or your pipeline fails) when it happens.

It does not attempt to counter freeze attacks (i.e. work around them) other than allowing you to have several sources that are accessed independently.  Such an attack will succeed to deny access to that source of updates during the validity window, and after it moves out of that window, it will effectively DoS apt upgrades (YMMV, and yes, this is arguably a bug in apt, and no, I am not sure it is still present in current apt from Debian unstable) until the local admin does her job and get rid of the attacked apt source.

That would still be a DoS, and not a remote root exploit, though.  TLS issues with apt before Debian "stretch" were likely to directly result in remote root access. Since Debian "stretch", the apt transports run under privilege separation (but **not** under strong jailing), so an attack against TLS will attack an unprivileged system user. This is less severe, but it could still lead to local privilege escalation later.

If you have a local proxy/mirror, IMHO you would be much better off using plain http to access that mirror from the docker clusters over your internal/neighborhood network, and using rsync to keep the mirror up-to-date with the Debian mirror network.
