### ISSUE TITLE
perl needs a security update

### ISSUE THREAD

**Issue by mt-clearhaus** [debuerreotype/docker-debian-artifacts#56]
https://www.debian.org/security/2018/dsa-4347

> Date Reported: 29 Nov 2018
> Affected Packages: perl
> CVEs: [CVE-2018-18311](https://security-tracker.debian.org/tracker/CVE-2018-18311), [CVE-2018-18312](https://security-tracker.debian.org/tracker/CVE-2018-18312), [CVE-2018-18313](https://security-tracker.debian.org/tracker/CVE-2018-18313), [CVE-2018-18314](https://security-tracker.debian.org/tracker/CVE-2018-18314)
> 
> For the stable distribution (stretch), these problems have been fixed in version 5.24.1-3+deb9u5.

```
$ docker run --rm -it debian:stretch bash -c 'dpkg -l | grep perl-base | sed -r "s/  +/  /g"'
ii  perl-base  5.24.1-3+deb9u4  amd64  minimal Perl system
```

Thanks :slightly_smiling_face:

**Comment by mt-clearhaus** [comment]
@yosifkit Pretty please :slightly_smiling_face: :santa:

**Comment by yosifkit** [comment]
We usually do rebuilds of the Debian base images about every 30 days to minimize image churn (since it will cause every image based on Debian to also be rebuilt).  The last Debian rebuild was merged 22 days ago (https://github.com/docker-library/official-images/pull/5062), so our normal release would probably be in the next week or so.

I don't think it is severe enough (or exploitable enough) to warrant an early rebuild.

**Comment by mt-clearhaus** [comment]
Cool, thank you for the clarification :+1:

**Comment by mt-clearhaus** [comment]
@tianon Is a rebuild getting closer?

**Comment by mt-clearhaus** [comment]
@yosifkit Is a rebuild getting closer?

(I am sorry that I erroneously mentioned tianon in the first version of this...)

**Comment by tianon** [comment]
I was thinking of doing one this morning, but then I realized that if I do that, we'll be absolutely slamming the automated builds tomorrow (which is Christmas Day, a Federal Holiday here in the states), so that wouldn't be terribly kind to those ops folks who might get paged for that event, so I'll plan to do a bump first thing after Christmas.

**Comment by tianon** [comment]
Update: snapshot.debian.org has been having some issues for a couple days so I haven't been able to get updated tarballs successfully built across all the architectures we need yet :disappointed:

**Comment by mt-clearhaus** [comment]
I see `debian:stretch` was rebuilt 12 days ago, including the upgrade of perl to version `5.24.1-3+deb9u5`. I think we can close this issue. Thanks :slightly_smiling_face:
