### ISSUE TITLE
stretch-slim's glibc and systemd have security vulnarabilities

### ISSUE THREAD

**Issue by ialidzhikov** [debuerreotype/docker-debian-artifacts#58]
```
docker run -ti debian:stretch-slim
ldd --version
ldd (Debian GLIBC 2.24-11+deb9u3) 2.24
...
```

`debian:stretch-slim` refers to glibc 2.24-11 which contains a lot of security vulnerabilities:
- CVE-2017-15804
- CVE-2017-15670
- CVE-2018-1000001
- CVE-2017-15671
- CVE-2017-12132
- CVE-2016-10228
- ...

systemd 232:
- CVE-2018-15688
- CVE-2018-15686
- CVE-2017-1000082
- CVE-2018-6954
- CVE-2017-18078
- CVE-2018-1049
- ...

Is there a way to provide an image that refers to a glibc with fixes for these security warnings?

**Comment by yosifkit** [comment]
Nope, we cannot provide a newer version of `libc-bin` with fixes for those CVE's since nothing is available. We can only provide what Debian upstream provides and this (`2.24-11+deb9u3`) is the newest available in Debian Stretch. As for the CVE's that are present, most have probably been deemed a "Minor issue" by the Debian Security team, like https://security-tracker.debian.org/tracker/CVE-2017-15804.

Related issues: https://github.com/docker-library/buildpack-deps/issues/46, https://github.com/docker-library/official-images/issues/2740#issuecomment-286253279
