### ISSUE TITLE
Jessie has been archived; sources.list should be updated

### ISSUE THREAD

**Issue by tobiasoort** [debuerreotype/docker-debian-artifacts#66]
see https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

this breaks apt-get update on everything based on debian:jessie.

**Comment by bourtemb** [comment]
https://www.mail-archive.com/debian-user@lists.debian.org/msg740481.html

>  I just noticed the wiki LTS/Using [1] has been updated. This seems the jessie-update/ should not be set anymore in the /etc/apt/sources.list.

[1] : https://wiki.debian.org/LTS/Using?action=diff&rev2=40&rev1=39

**Comment by olliemath** [comment]
For those reading this that need a quick work-around, it suffices to add this to your dockerfile before any calls to apt-get update
```docker
RUN sed -i '/jessie-updates/d' /etc/apt/sources.list  # Now archived
```

**Comment by cadwallion** [comment]
👋 Will there be an update to the `debian:jessie` image to remove this?  Jessie is still LTS, but LTS is not supposed to use `-updates` which is why it's missing.

**Comment by mayank-unbxd** [comment]
sigh of relief, images are now getting built 
thanks @Totktonada

**Comment by blockjon** [comment]
I used this in my docker build:

`RUN sed -i '/jessie-updates/d' /etc/apt/sources.list`

however i end up getting:

```
apt-get install -y build-essential
"E: Unable to correct problems, you have held broken packages."
```

Please advise.

**Comment by blockjon** [comment]
> For those reading this that need a quick work-around, it suffices to add this to your dockerfile before any calls to apt-get update
> 
> ```
> RUN sed -i '/jessie-updates/d' /etc/apt/sources.list  # Now archived
> ```
@olliemath thanks for this ...

I used your technique in my docker build...

`RUN sed -i '/jessie-updates/d' /etc/apt/sources.list`

however building my container still does not work. I get:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: gcc (>= 4:4.9.1) but it is not going to be installed
                   Depends: g++ (>= 4:4.9.1) but it is not going to be installed
                   Depends: dpkg-dev (>= 1.17.11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

These builds were working just yesterday so I'm positive I'm affected by this issue. Do you have any insight as to how I could resolve this? I asked this earlier and someone marked my question as off topic but I'm not sure how this is could be considered off topic. The reason I think this is *on* topic is because I'm trying to recover from being stranded after jessie was archived. If you could just steer me in the right direction, that would help me and anybody else who this has happened to.

**Comment by tianon** [comment]
@blockjon this is not a support forum, which is why your comment got marked off-topic (the workaround is confirmed working for other folks, so there's something particular about what you're doing that's causing your issue) -- for folks to help you, you'll have to provide more detail such as a full `Dockerfile` to reproduce; for example, are you doing `apt-get update` after you invoke `sed`? (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get)

For further help adapting the above-mentioned workaround to your environment, I'd recommend trying user support channels such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by tianon** [comment]
PR up! https://github.com/docker-library/official-images/pull/5609

**Comment by tianon** [comment]
For any who haven't seen it, we're (somewhat long-since now) live!

```console
$ docker run --rm debian:jessie-slim grep '^deb ' /etc/apt/sources.list
deb http://deb.debian.org/debian jessie main
deb http://security.debian.org/debian-security jessie/updates main
```

**Comment by tianon** [comment]
(Also, please migrate off Jessie ASAP -- the clock is _ticking_!!)

**Comment by marioguio** [comment]
i have this error:
sudo sed -i '/jessie-updates/d' /etc/apt/sources.list && apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
Exited with code 100

**Comment by tianon** [comment]
This issue has been resolved to the extent it is going to be.

For further support/assistance, I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
