### ISSUE TITLE
Question for debian on mips

### ISSUE THREAD

**Issue by ydcool** [debuerreotype/docker-debian-artifacts#84]
I noticed that the [multiarch/debian-debootstrap](https://github.com/multiarch/debian-debootstrap) has fully support for mips and mips64el, but not available here, is there any difference between the official debian rootfs tarballs and the multiarch's  tarballs built in that way?  Could we add the branch `dist-mips` and `dist-mips64el` and push the tarballs like the @multiarch did? thanks!

https://github.com/multiarch/debian-debootstrap/blob/9cf15acba89bcb5e1c2ca22443193a67c8b70eea/update.sh#L48

**Comment by tianon** [comment]
I was planning to add `mips64el` once https://github.com/docker-library/official-images/issues/6709 is resolved -- does it really make sense to add `mips` as well?  Especially since it's [deprecated from Debian 11 onwards](https://lists.debian.org/debian-release/2019/08/msg00582.html)?  What about `mipsel`?

(I have to admit my experience with these architectures is very limited, but I have to wonder how `mipsel` is going to fare in the future given that `mips` is no longer supported, and thus wonder whether it's worth the effort.)

**Comment by ydcool** [comment]
No actually I don't care much about the `mips` and `mipsel`, just wondering how the `qemu-debootstrap` could build debian rootfs tarballs for those arch, futher more could we release some debian images into the `hub.docker.com/u/mips64el` in this way? because our work was blocked here...

**Comment by tianon** [comment]
Unfortunately we've had *way* too many bad experiences relying on QEMU on a large scale so we don't officially use it for anything more than local testing.

Additionally, even if we add `mips64le` here, it wouldn't be acceptable/buildable downstream until https://github.com/docker-library/official-images/issues/6709 is resolved anyhow. :disappointed:

**Comment by ydcool** [comment]
Alright...


 
---Original---

**Comment by tianon** [comment]
This is almost done -- tarballs are built and being "collected" into this repository now! :+1:

**Comment by ydcool** [comment]
> This is almost done -- tarballs are built and being "collected" into this repository now! 👍

Greeeeeeat!
