### ISSUE TITLE
3 high vulnerabilities in debian:buster-slim docker image 

### ISSUE THREAD

**Issue by jayclover** [debuerreotype/docker-debian-artifacts#91]
3 HIGH Vulnerabilities found in os package type:
 - bash ( [CVE-2019-18276](https://nvd.nist.gov/vuln/detail/CVE-2019-18276))
 - tar ( [CVE-2019-9923](https://nvd.nist.gov/vuln/detail/CVE-2019-9923))
 - libgcrypt20 ( [CVE-2018-6829](https://nvd.nist.gov/vuln/detail/CVE-2018-6829))

Our security system detect listed 3 vulnerabilities in the latest docker image debian:buster-slim.
Could anyone help check and fix them? Thanks.

**Comment by tianon** [comment]
See https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves -- here's my own testing:

```console
$ docker pull debian:buster-slim
buster-slim: Pulling from library/debian
Digest: sha256:9d08b5e6b5f23a61634da3d08d654a24b06946f4ef7f6dd8b75e52c6baa1f1b0
Status: Image is up to date for debian:buster-slim
docker.io/library/debian:buster-slim

$ docker run -it --rm debian:buster-slim
root@86860db1fff3:/# apt-get update -qq
root@86860db1fff3:/# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

So even if these are valid, there's nothing we can do because Debian has declined to update:

- https://security-tracker.debian.org/tracker/CVE-2019-18276: "`<no-dsa> (Minor issue)`"
- https://security-tracker.debian.org/tracker/CVE-2019-9923: "`Crash in CLI tool, no security impact`"
- https://security-tracker.debian.org/tracker/CVE-2018-6829: "`This is not a vulnerability in libgcrypt, but in an application using it in an insecure manner`"
