### ISSUE TITLE
Package list (apt-get update)

### ISSUE THREAD

**Issue by alejandro-colomar** [debuerreotype/docker-debian-artifacts#95]
In Alpine Linux docker images, they have the package list in the image, so you only need to install the packages you want without having to download the list.

This is good for the following reason:

If I want some very specific version, I use the image with its SHA, and get the same versions of packages everywhere, and if I install a package, it will always be the same exact version.

With Debian docker images, I'm forced to run ``apt-get update`` at the beginning, so it may introduce new versions every time I run it, which I don't want.

Please, include the package list with the image, so I only run ``apt-get update`` if I really want the latest version.

**Comment by tianon** [comment]
There's a few things at play here, so I'm going to try my best to cover everything.

> In Alpine Linux docker images, they have the package list in the image, so you only need to install the packages you want without having to download the list.

This isn't strictly true:

```console
$ docker pull alpine:3.11
3.11: Pulling from library/alpine
Digest: sha256:9a839e63dad54c3a6d1834e29692c8492d93f90c59c978c1ed79109ea4fb9a54
Status: Image is up to date for alpine:3.11
docker.io/library/alpine:3.11
$ docker run -d --name test alpine:3.11 apk update
5eef65f9a5d671307b2c5ec35347ee4c2910c73bdf44fe1a69251640bea08867
$ docker diff test
C /var
C /var/cache
C /var/cache/apk
A /var/cache/apk/APKINDEX.70f61090.tar.gz
A /var/cache/apk/APKINDEX.ca2fea5b.tar.gz
$ docker run -it --rm alpine:3.11 ls -l /var/cache/apk
total 0
```

When you use `apk`, it will auto-fetch the package lists when they are missing, and it also auto-removes them if you use `--no-cache` (which is really handy for keeping your images small, since those downloaded index files are ~1.5MB, which doesn't seem like much until you compare it to the size of the entire `alpine:3.11` base image at ~5.61MB).

> If I want some very specific version, I use the image with its SHA, and get the same versions of packages everywhere, and if I install a package, it will always be the same exact version.

This would be a fantastic property!  Unfortunately, the Debian archive does *not* keep old `.deb` files around, which is the main reason we remove the package lists.  Once a new version of a given package is uploaded to https://deb.debian.org/debian/, the old version typically goes away very quickly (and there are definitely not ever three versions of a given package for a given suite at any given time).

So if we left the package list files in the image, what you would experience instead is that a lot of things you tried to `apt-get install` would 404, breaking your build.

If you want point-in-time snapshots, you have to use the https://snapshot.debian.org/ service, but it is not maintained in such a way that it's recommended for widespread use (it's computationally expensive on the Debian infrastructure), so we cannot use it for general-purpose images (also, it won't get security updates as an intended feature, so for that reason is *also* not a great plan for most users).

That being said, there are copies of the base images we publish configured to use that service available at https://hub.docker.com/r/debian/snapshot.

Hopefully that helps explain why we don't include the package lists, and why it doesn't really make sense for us to do so.
